language: python
python:
- '3.6'
- '3.7'
install:
- python setup.py develop
- pip install coveralls
script: coverage run --source=pydpc setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: cwehmeyer-deployment
  password:
    secure: VBppPw+pO2IQCvFEeMthXB/4GB1LjmbzPFsqh4+3xP6R0ji6Cfa0hKqGim58/t8RVrm6EDNK4B9IYKW3FaP96KMysgqKG4EfYafvC2KVe4a14mJeXzmijKYZQ/bcN2xHJzPGizS6jYJ3e2DEwv3KtQ271Je9aVlL0Tm3ePybf8/QVwn38C7L+Jhtjr6JAGzVsxrot9/K6N7JpErBX45Vsbn2BeFciVTR+0nkJBneTgVfTXt69vLlwNspTcqX8Hd7QAtLcWiV5zMyJ/7lzXqm36iEgU92yONeeDRgbM2RCFL2o5BWZK01JcZIHKrs9DETu2GskbgysNnXH2A2r7T9ThMJ916U9hBlVYBBTnHV6uSuRPuxoQhOnZ3eJzvBqOjJs2TEKRaeN0YUN4XGUss/8X6VBRmjO8oDBVK5kY5/d99wO9ni+w7KuvciPGdF+f1gs7ATS6p8xwsgw37IkEoRrbOxCI7k3XWUcMoBcDLZKRwiOb42fRZUmFmEokVaL31MgYLSEyVl7/EF8kPYIxCmZd1GB1Vp7bMYx+Lx/CqRxXW8pFYVHVTRNORXGN0XxrmDFwt4/URG2S8H5o0PPYx5p4/aYyqLHu5Ru0UI2lo7mntH081JBN5QNqjrWhEz9lm9lSp3wd2aIlXnxCZgfMkrx6GugbJTmqA7UZetzDik1w4=
  on:
    tags: true
    distributions: sdist
    repo: cwehmeyer/pydpc
    branch: master
